# Generated by Django 2.0 on 2018-03-24 21:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nucleus', '0003_auto_20180324_2100'),
        ('teams', '0003_auto_20180324_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='DivisionSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Division')),
            ],
            options={
                'ordering': ('division__number', 'season__number'),
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=256)),
                ('num_series_per_season', models.IntegerField()),
                ('num_games_per_series', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LeagueRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nucleus.TeamMember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('matchid', models.CharField(blank=True, max_length=32, null=True)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_lost', to='teams.Team')),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('number', models.IntegerField(editable=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('division_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.DivisionSeason')),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_lost', to='teams.Team')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_as_team_a', to='teams.Team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_as_team_b', to='teams.Team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_won', to='teams.Team')),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ('division_season__division__number', 'division_season__season__number', 'start_date'),
            },
        ),
        migrations.AddField(
            model_name='match',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Series'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_won', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='leagues', to='league.Season'),
        ),
        migrations.AddField(
            model_name='divisionseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.Season'),
        ),
        migrations.AddField(
            model_name='divisionseason',
            name='teams',
            field=models.ManyToManyField(related_name='division_seasons', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='division',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.League'),
        ),
        migrations.AddField(
            model_name='division',
            name='seasons',
            field=models.ManyToManyField(related_name='divisions', through='league.DivisionSeason', to='league.Season'),
        ),
        migrations.AlterUniqueTogether(
            name='division',
            unique_together={('league', 'number')},
        ),
    ]
