# Generated by Django 2.0 on 2018-03-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='description',
            field=models.CharField(blank=True, help_text='A short description about this league.', max_length=512, null=True),
        ),
    ]
