# Generated by Django 2.0 on 2018-03-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_auto_20180325_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='number',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('number', 'league')},
        ),
    ]
