# Generated by Django 2.0 on 2018-04-12 02:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_leagueregistration_registered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='divisionseason',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 12, 2, 30, 57, 79862, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='divisionseason',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2018, 4, 12, 2, 31, 0, 15710, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
