# Generated by Django 2.0 on 2018-04-13 02:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_auto_20180412_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesTimeWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('division_season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.DivisionSeason')),
            ],
            options={
                'ordering': ('division_season__division__number', 'division_season__season__number', 'start_date'),
            },
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'Series'},
        ),
        migrations.RemoveField(
            model_name='series',
            name='division_season',
        ),
        migrations.RemoveField(
            model_name='series',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='series',
            name='start_date',
        ),
        migrations.AddField(
            model_name='series',
            name='series_time_window',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='league.SeriesTimeWindow'),
        ),
    ]
