# Generated by Django 2.0 on 2018-03-04 21:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('home_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('match_date', models.DateField(blank=True, null=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_team', to='teams.Team')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_team', to='teams.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
