# Generated by Django 2.0 on 2018-03-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20180314_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueseries',
            name='league_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.LeagueSeason'),
        ),
        migrations.AlterField(
            model_name='leagueseries',
            name='num_games',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leagueseries',
            name='team_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_played_as_team_1', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='leagueseries',
            name='team_b',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_played_as_team_2', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.LeagueSeries'),
        ),
    ]
