# Generated by Django 2.0 on 2018-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20180318_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueseason',
            name='number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
