# Generated by Django 2.0 on 2018-03-18 14:16

from django.db import migrations


def forwards(apps, schema_editor):
    LeagueSeason = apps.get_model('schedule.LeagueSeason')
    LeagueSeries = apps.get_model('schedule.LeagueSeries')

    LeagueSeries.objects.all().delete()
    LeagueSeason.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_leagueseason_number'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
