# Generated by Django 2.0 on 2018-03-18 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_delete_seasons_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leagueseries',
            name='league_season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LeagueSeason'),
        ),
        migrations.AlterField(
            model_name='match',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.LeagueSeries'),
        ),
    ]
