# Generated by Django 2.0 on 2018-03-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20180318_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leagueseries',
            options={'verbose_name_plural': 'League series'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterField(
            model_name='leagueseason',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
