# Generated by Django 2.0 on 2018-04-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0004_auto_20180407_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position',
            field=models.IntegerField(choices=[(1, 'Player'), (2, 'Sub')], default=1),
        ),
    ]
