# Generated by Django 2.0 on 2018-04-12 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nucleus', '0005_teammember_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='position',
            new_name='role',
        ),
    ]
